// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {
      '404': { id: '404', path: '*', parentId: 'DocLayout' },
      'dumi-context-layout': {
        id: 'dumi-context-layout',
        path: '/',
        isLayout: true,
      },
      DocLayout: {
        id: 'DocLayout',
        path: '/',
        parentId: 'dumi-context-layout',
        isLayout: true,
      },
      'docs/guide/conventional-routing': {
        path: 'guide/conventional-routing',
        id: 'docs/guide/conventional-routing',
        parentId: 'DocLayout',
      },
      'docs/guide/project-structure': {
        path: 'guide/project-structure',
        id: 'docs/guide/project-structure',
        parentId: 'DocLayout',
      },
      'docs/guide/page-config': {
        path: 'guide/page-config',
        id: 'docs/guide/page-config',
        parentId: 'DocLayout',
      },
      'docs/guide/initialize': {
        path: 'guide/initialize',
        id: 'docs/guide/initialize',
        parentId: 'DocLayout',
      },
      'docs/guide/write-demo': {
        path: 'guide/write-demo',
        id: 'docs/guide/write-demo',
        parentId: 'DocLayout',
      },
      'docs/config/markdown': {
        path: 'config/markdown',
        id: 'docs/config/markdown',
        parentId: 'DocLayout',
      },
      'docs/guide/upgrading': {
        path: 'guide/upgrading',
        id: 'docs/guide/upgrading',
        parentId: 'DocLayout',
      },
      'docs/guide/markdown': {
        path: 'guide/markdown',
        id: 'docs/guide/markdown',
        parentId: 'DocLayout',
      },
      'docs/guide/page-tab': {
        path: 'guide/page-tab',
        id: 'docs/guide/page-tab',
        parentId: 'DocLayout',
      },
      'docs/theme/default': {
        path: 'theme/default',
        id: 'docs/theme/default',
        parentId: 'DocLayout',
      },
      'docs/config/index': {
        path: 'config',
        id: 'docs/config/index',
        parentId: 'DocLayout',
      },
      'docs/config/demo': {
        path: 'config/demo',
        id: 'docs/config/demo',
        parentId: 'DocLayout',
      },
      'docs/guide/index': {
        path: 'guide',
        id: 'docs/guide/index',
        parentId: 'DocLayout',
      },
      'docs/theme/index': {
        path: 'theme',
        id: 'docs/theme/index',
        parentId: 'DocLayout',
      },
      'docs/guide/i18n': {
        path: 'guide/i18n',
        id: 'docs/guide/i18n',
        parentId: 'DocLayout',
      },
      'docs/guide/faq': {
        path: 'guide/faq',
        id: 'docs/guide/faq',
        parentId: 'DocLayout',
      },
      'docs/theme/api': {
        path: 'theme/api',
        id: 'docs/theme/api',
        parentId: 'DocLayout',
      },
      'docs/index': { path: '', id: 'docs/index', parentId: 'DocLayout' },
      'demo-render': {
        id: 'demo-render',
        path: '~demos/:id',
        parentId: 'dumi-context-layout',
      },
    },
    routeComponents: {
      '404': React.lazy(
        () =>
          import(
            /* webpackChunkName: "__Users__logeast__Documents__gitee__dumi-theme-vite__node_modules__dumi__dist__client__pages__404" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/node_modules/dumi/dist/client/pages/404.js'
          ),
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/.dumi/tmp/dumi/theme/ContextWrapper.tsx'
          ),
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__theme__layouts__DocLayout__index" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/.dumi/theme/layouts/DocLayout/index.tsx'
          ),
      ),
      'docs/guide/conventional-routing': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__conventional-routing.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/guide/conventional-routing.md'
          ),
      ),
      'docs/guide/project-structure': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__project-structure.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/guide/project-structure.md'
          ),
      ),
      'docs/guide/page-config': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__page-config.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/guide/page-config.md'
          ),
      ),
      'docs/guide/initialize': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__initialize.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/guide/initialize.md'
          ),
      ),
      'docs/guide/write-demo': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__write-demo.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/guide/write-demo.md'
          ),
      ),
      'docs/config/markdown': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__config__markdown.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/config/markdown.md'
          ),
      ),
      'docs/guide/upgrading': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__upgrading.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/guide/upgrading.md'
          ),
      ),
      'docs/guide/markdown': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__markdown.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/guide/markdown.md'
          ),
      ),
      'docs/guide/page-tab': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__page-tab.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/guide/page-tab.md'
          ),
      ),
      'docs/theme/default': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__theme__default.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/theme/default.md'
          ),
      ),
      'docs/config/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__config__index.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/config/index.md'
          ),
      ),
      'docs/config/demo': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__config__demo.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/config/demo.md'
          ),
      ),
      'docs/guide/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__index.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/guide/index.md'
          ),
      ),
      'docs/theme/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__theme__index.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/theme/index.md'
          ),
      ),
      'docs/guide/i18n': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__i18n.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/guide/i18n.md'
          ),
      ),
      'docs/guide/faq': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__faq.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/guide/faq.md'
          ),
      ),
      'docs/theme/api': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__theme__api.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/theme/api.md'
          ),
      ),
      'docs/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__index.md" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/index.md'
          ),
      ),
      'demo-render': React.lazy(
        () =>
          import(
            /* webpackChunkName: "__Users__logeast__Documents__gitee__dumi-theme-vite__node_modules__dumi__dist__client__pages__Demo__index" */ '/Users/logeast/Documents/gitee/dumi-theme-vite/node_modules/dumi/dist/client/pages/Demo/index.js'
          ),
      ),
    },
  };
}
