// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"docs/test":{"path":"test","id":"docs/test","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}},
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "__Users__logeast__Documents__gitee__dumi-theme-vite__node_modules__.pnpm__dumi_2.0.2_r2aw3peds5c3otmdu3prwcbm3y__node_modules__dumi__dist__client__pages__404" */'/Users/logeast/Documents/gitee/dumi-theme-vite/node_modules/.pnpm/dumi@2.0.2_r2aw3peds5c3otmdu3prwcbm3y/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/logeast/Documents/gitee/dumi-theme-vite/example/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "__Users__logeast__Documents__gitee__dumi-theme-vite__node_modules__.pnpm__dumi_2.0.2_r2aw3peds5c3otmdu3prwcbm3y__node_modules__dumi__theme-default__layouts__DocLayout__index" */'/Users/logeast/Documents/gitee/dumi-theme-vite/node_modules/.pnpm/dumi@2.0.2_r2aw3peds5c3otmdu3prwcbm3y/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/index.md')),
'docs/test': React.lazy(() => import(/* webpackChunkName: "docs__test.md" */'/Users/logeast/Documents/gitee/dumi-theme-vite/example/docs/test.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "__Users__logeast__Documents__gitee__dumi-theme-vite__node_modules__.pnpm__dumi_2.0.2_r2aw3peds5c3otmdu3prwcbm3y__node_modules__dumi__dist__client__pages__Demo__index" */'/Users/logeast/Documents/gitee/dumi-theme-vite/node_modules/.pnpm/dumi@2.0.2_r2aw3peds5c3otmdu3prwcbm3y/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
