// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, Helmet, useAppData, useClientLoaderData, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/logeast/Documents/gitee/dumi-theme-vite/node_modules/.pnpm/@umijs+renderer-react@4.0.32_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react';
export type {  History } from '/Users/logeast/Documents/gitee/dumi-theme-vite/node_modules/.pnpm/@umijs+renderer-react@4.0.32_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/logeast/Documents/gitee/dumi-theme-vite/node_modules/.pnpm/umi@4.0.32_r2aw3peds5c3otmdu3prwcbm3y/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
// plugins types.d.ts
export { defineApp } from './core/defineApp'
export type {  RuntimeConfig } from './core/defineApp'
