// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/logeast/Documents/dumi-theme-vite/node_modules/.pnpm/dumi@2.0.2_xgbqj6fguo7kan2ufc2v2cdr6u/node_modules/dumi/theme-default/slots/ContentTabs/index.js';
