// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/logeast/Documents/gitee/dumi-theme-vite/node_modules/.pnpm/dumi@2.0.2_r2aw3peds5c3otmdu3prwcbm3y/node_modules/dumi/theme-default/slots/ContentTabs/index.js';
