// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/logeast/Documents/gitee/dumi-theme-vite/node_modules/dumi/theme-default/slots/PreviewerActions/index.js';
