// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { history, useOutlet } from 'dumi';
import { useEffect, useRef, useState } from 'react';
import { locales } from '../locales/config';
import { components, demos } from '../meta';
import { SiteContext } from '/Users/logeast/Documents/gitee/dumi-theme-vite/node_modules/dumi/dist/client/theme-api/context.js';

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(true);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      // mark loading when route change, page component will set false when loaded
      setLoading(true);

      // scroll to top when route changed
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  return (
    <SiteContext.Provider
      value={{
        pkg: {},
        demos,
        components,
        locales,
        loading,
        setLoading,
        themeConfig: {
          footer:
            'Copyright © 2022 | Powered by <a href="https://d.umijs.org" target="_blank" rel="noreferrer">dumi</a>',
        },
      }}
    >
      {outlet}
    </SiteContext.Provider>
  );
}
