name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: "Build&Test: node-16, ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v2.2.4

      # - name: Set node version
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      #     # cache: 'pnpm'

      # - name: Install deps
      #   # run: pnpm install
      #   run: npm install

      # - name: Build
      #   # run: pnpm prepublishOnly
      #   run: npm run prepublishOnly

      - name: Set node version to 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
          # cache: 'pnpm'

      - name: Install deps
        # run: pnpm install
        run: npm install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

      - name: push tags
        run: |
          git config user.name logeast
          git config user.email logeast@outlook.com
          npm version patch
          git push --follow-tags
          git push

      - name: Publish package
        # run: pnpm -r --no-git-checks publish
        run: npm -r --no-git-checks publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # lint:
  #   timeout-minutes: 10
  #   runs-on: ubuntu-latest
  #   name: 'Lint: node-16, ubuntu-latest'
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v2.2.4

  #     - name: Set node version to 16
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         cache: 'pnpm'

  #     - name: Install deps
  #       run: pnpm install

  #     - name: Build
  #       run: pnpm run build

  #     - name: Lint
  #       run: pnpm run lint
