name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: 'Build&Test: node-16, ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install deps
        # run: pnpm install
        run: npm install

      - name: Build
        run: pnpm prepublishOnly
        run: npm run prepublishOnly

  # lint:
  #   timeout-minutes: 10
  #   runs-on: ubuntu-latest
  #   name: 'Lint: node-16, ubuntu-latest'
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v2.2.4

  #     - name: Set node version to 16
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         cache: 'pnpm'

  #     - name: Install deps
  #       run: pnpm install

  #     - name: Build
  #       run: pnpm run build

  #     - name: Lint
  #       run: pnpm run lint
